# Generated by Django 5.2.9 on 2025-12-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classchatmessage",
            old_name="mesasge",
            new_name="content",
        ),
    ]
